//! Bounded Wi-Fi event vocabulary for catalog v1.3.
//!
//! The inventory is deliberately limited to 13 raw frame events, nine true
//! tracker/FSM outcomes, two principal summaries, and two TCP cross-layer
//! streams. `wifi.client.twt_outcome` is retained only for the in-scope
//! `TwtSleepCorrelatesWithRto` cross-layer rule; it is not a standalone
//! ClientIssue output. Existing `wifi.deauth_burst` and `wifi.rf_telemetry`
//! remain in the base catalog.

use airpulse_dsl_types::ScopeType;

pub(crate) struct WifiEventSpec {
    pub name: &'static str,
    pub scope: ScopeType,
    pub extra_fields: &'static [&'static str],
    pub pii_fields: &'static [&'static str],
}

pub(crate) const WIFI_EVENT_SPECS: &[WifiEventSpec] = &[
    // Raw management/control/data frames (13).
    WifiEventSpec {
        name: "wifi.mgmt.beacon",
        scope: ScopeType::AccessPoint,
        extra_fields: &["channel", "rssi_dbm", "dtim_period", "has_rsn"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.mgmt.probe_req",
        scope: ScopeType::ClientMac,
        extra_fields: &["freq_mhz"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.mgmt.probe_resp",
        scope: ScopeType::AccessPoint,
        extra_fields: &["rssi_dbm"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.mgmt.auth",
        scope: ScopeType::ClientMac,
        extra_fields: &["seq", "status", "algorithm"],
        pii_fields: &["bssid"],
    },
    WifiEventSpec {
        name: "wifi.mgmt.assoc_req",
        scope: ScopeType::ClientMac,
        extra_fields: &["ft_pmkid_hint"],
        pii_fields: &["bssid"],
    },
    WifiEventSpec {
        name: "wifi.mgmt.assoc_resp",
        scope: ScopeType::AccessPoint,
        extra_fields: &["status"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.mgmt.deauth",
        scope: ScopeType::ClientMac,
        extra_fields: &[
            "initiator",
            "reason",
            "protected",
            "is_deauth_or_disassoc",
            "initiator_code",
        ],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.mgmt.action",
        scope: ScopeType::AccessPoint,
        extra_fields: &[
            "category",
            "protected",
            "initiator_code",
            "associated",
            "csa_present",
        ],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.mgmt.cts",
        scope: ScopeType::AccessPoint,
        extra_fields: &["nav_us"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.ctrl.rts",
        scope: ScopeType::ClientMac,
        extra_fields: &[],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.ctrl.bar",
        scope: ScopeType::AccessPoint,
        extra_fields: &[],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.data.frame",
        scope: ScopeType::ClientMac,
        extra_fields: &["retry", "protected", "tid", "rate_kbps", "rssi_dbm"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.eapol.frame",
        scope: ScopeType::ClientMac,
        extra_fields: &["frame_type"],
        pii_fields: &[],
    },
    // True tracker/FSM outcomes (9).
    WifiEventSpec {
        name: "wifi.client.auth_outcome",
        scope: ScopeType::ClientMac,
        extra_fields: &["auth_failed", "deauth_reason"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.client.eap_outcome",
        scope: ScopeType::ClientMac,
        extra_fields: &[
            "outcome_code",
            "state_code",
            "nak_method_count",
            "idle_timeout",
            "retry_count",
        ],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.client.roam_outcome",
        scope: ScopeType::ClientMac,
        extra_fields: &["success", "latency_ms", "reassoc", "status_code", "ft"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.client.dhcp_outcome",
        scope: ScopeType::ClientMac,
        extra_fields: &["pending_ms", "ack_seen", "outcome_code"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.client.dhcpv6_outcome",
        scope: ScopeType::ClientMac,
        extra_fields: &["pending_ms", "reply_seen"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.client.dns_outcome",
        scope: ScopeType::ClientMac,
        extra_fields: &[
            "pending_ms",
            "response_seen",
            "latency_ms",
            "resolver_mismatch",
        ],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.client.assoc_pending",
        scope: ScopeType::ClientMac,
        extra_fields: &["pending_ms", "response_seen"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.client.sae_outcome",
        scope: ScopeType::ClientMac,
        extra_fields: &["sae_seen", "deauth_seen", "eap_seen"],
        pii_fields: &[],
    },
    WifiEventSpec {
        name: "wifi.client.twt_outcome",
        scope: ScopeType::ClientMac,
        extra_fields: &["twt_rejected"],
        pii_fields: &[],
    },
    // Principal typed summaries (2). Units are fixed by
    // docs/migration/wifi-to-adgl-ids.md §2.
    WifiEventSpec {
        name: "wifi.ap.summary",
        scope: ScopeType::AccessPoint,
        extra_fields: &[
            "gap_us",
            "expected_interval_us",
            "missed_count",
            "jitter_centi_ratio",
            "sample_count",
            "probe_age_ms",
            "beacon_age_ms",
            "beacon_rates_hash",
            "assoc_rates_hash",
            "consecutive_count",
            "max_gap_ms",
            "bar_count",
            "window_ms",
            "peer_rates_hash",
            "rates_hash",
            "ap_count",
            "has_rsn",
            "max_rate_kbps",
            "has_ht_cap",
            "streak",
            "channel_count",
            "rssi_dbm",
            "delta_db",
            "frame_count",
            "retry_permille",
            "weak_security",
            "client_count",
            "target_is_dfs",
            "ssid_count",
            "dtim_period",
            "util_centipercent",
            "security_fingerprint_count",
            "active_sta_count",
            "min_sta_frames",
            "ap_retry_permille",
            "client_retry_mean_permille",
            "peer_bssid_count",
            "high_co_channel_present",
            "is_6ghz",
            "has_he_cap",
            "eht_width_code",
            "has_eht_cap",
            "has_puncturing_bitmap",
            "has_visible_ssid",
            "has_supported_rates",
            "collision",
            "unencrypted_traffic_leak",
        ],
        pii_fields: &["bssid"],
    },
    WifiEventSpec {
        name: "wifi.client.summary",
        scope: ScopeType::ClientMac,
        extra_fields: &[
            "streak",
            "ps_poll_count",
            "state_code",
            "count",
            "window_ms",
            "connected",
            "snr_db",
            "rate_kbps",
            "data_frame_count",
            "absence_ms",
            "has_ul",
            "has_dl",
            "ps_beacon_streak",
            "ft",
            "pmkid_count",
            "protected",
            "assoc_age_ms",
            "tid",
            "rssi_dbm",
            "neighbor_delta_db",
            "distinct_ap_count",
            "probe_count",
            "probe_5g_count",
            "probe_24g_count",
            "associated_5g",
            "failed_count",
            "ft_or_bss_tm",
            "seq_delta",
            "retry",
            "client_generation_code",
            "ap_generation_code",
            "mlo_present",
            "saw_6ghz",
            "saw_psc",
            "unique_servfail_count",
            "nxdomain_count",
            "server_rst_count",
            "ap_retry_permille",
            "auth_latency_ms",
            // W2 append-only, semantically distinct windows/row kinds.
            "summary_kind_code",
            "probe_count_10s",
            "deauth_count_30s",
            "disconnect_count_60s",
            "distinct_ap_count_60s",
            "emlsr_transition_count_60s",
            "band_probe_count_60s",
            "band_probe_5g_count_60s",
            "band_probe_24g_count_60s",
            "psc_probe_count_120s",
            "dns_servfail_unique_count",
            "dns_nxdomain_count",
            "captive_rst_count_120s",
            "ft_failure_count_60s",
            "tid_has_ul",
            "tid_has_dl",
            "saw_eapol",
        ],
        pii_fields: &["client_mac"],
    },
    // Cross-layer temporal sample required by two W0 session rules.
    WifiEventSpec {
        name: "tcp.throughput_sample",
        scope: ScopeType::Session,
        extra_fields: &[
            "before_peak_kbps",
            "after_trough_kbps",
            "mean_throughput_kbps",
        ],
        pii_fields: &[],
    },
    // Temporal RTT spike required by RoamingCausedStall.
    WifiEventSpec {
        name: "tcp.rtt_sample",
        scope: ScopeType::Session,
        extra_fields: &["rtt_ms", "baseline_rtt_ms"],
        pii_fields: &[],
    },
];
