//! Catalog problem schemas.

use airpulse_dsl_types::{ScopeType, Severity};

use crate::ProblemSchema;
use crate::helpers::problem;
use crate::wifi;

/// Returns all catalog problem schemas.
pub(crate) fn all_problems() -> Box<[ProblemSchema]> {
    [
        // --- Legacy seed problems (10-catalog-abi.md §4) ---
        problem(
            "XlIcmpTcpMss",
            &[ScopeType::Session],
            "l3_pmtud_blackhole",
            None,
        ),
        problem(
            "CableDisconnected",
            &[ScopeType::Port],
            "ap_port_cable_disconnected",
            None,
        ),
        problem(
            "SpanningTreeInstability",
            &[ScopeType::Vlan],
            "l3_stp_spanning_tree",
            None,
        ),
        problem(
            "ClientOnboardingFailure",
            &[ScopeType::Vlan],
            "l3_dot1x_wired",
            None,
        ),
        problem(
            "WlanRadiusOutage",
            &[ScopeType::Vlan],
            "ap_wlan_radius_outage",
            None,
        ),
        problem(
            "DeviceUnreachable",
            &[ScopeType::Global],
            "ap_device_unreachable",
            None,
        ),
        problem(
            "AmbiguousDiagnosis",
            &[
                ScopeType::Session,
                ScopeType::Port,
                ScopeType::ClientMac,
                ScopeType::Vlan,
                ScopeType::AccessPoint,
                ScopeType::Global,
            ],
            "ap_ambiguous",
            Some(Severity::Medium),
        ),
        // --- TCP problems (legacy sarif_id families) ---
        problem(
            "TcpZeroWindow",
            &[ScopeType::Session],
            "tcp_zero_window",
            None,
        ),
        problem(
            "TcpCaptureScopeMiddlebox",
            &[ScopeType::Session],
            "tcp_capture_scope_middlebox",
            None,
        ),
        problem(
            "TcpChecksumLink",
            &[ScopeType::Session],
            "tcp_checksum_link",
            None,
        ),
        problem(
            "TcpIncompleteHandshake",
            &[ScopeType::Session],
            "tcp_incomplete_handshake",
            None,
        ),
        problem("TcpLossSack", &[ScopeType::Session], "tcp_loss_sack", None),
        problem(
            "TcpSpuriousReordering",
            &[ScopeType::Session],
            "tcp_spurious_reordering",
            None,
        ),
        problem(
            "TcpPacketLoss",
            &[ScopeType::Session],
            "tcp_packet_loss",
            None,
        ),
        problem(
            "TcpRadioChannel",
            &[ScopeType::Session],
            "tcp_radio_channel",
            None,
        ),
        problem(
            "TcpRwinLimited",
            &[ScopeType::Session],
            "tcp_rwin_limited",
            None,
        ),
        problem(
            "TcpBufferbloat",
            &[ScopeType::Session],
            "tcp_bufferbloat",
            None,
        ),
        problem(
            "TcpSenderBuffer",
            &[ScopeType::Session],
            "tcp_sender_buffer",
            None,
        ),
        problem(
            "TcpUplinkLatency",
            &[ScopeType::Session],
            "tcp_uplink_latency",
            None,
        ),
        problem("TcpMiddlebox", &[ScopeType::Session], "tcp_middlebox", None),
        problem(
            "TcpSlowRamping",
            &[ScopeType::Session],
            "tcp_slow_ramping",
            None,
        ),
        // --- L3 problems (legacy sarif_id families) ---
        problem(
            "L3IcmpUnreachablePath",
            &[ScopeType::Session],
            "l3_icmp_unreachable_path",
            None,
        ),
        problem(
            "L3IcmpControlPlane",
            &[ScopeType::Session],
            "l3_icmp_control_plane",
            None,
        ),
        problem(
            "L3ArpDuplicateL2",
            &[ScopeType::Session, ScopeType::Vlan],
            "l3_arp_duplicate_l2",
            None,
        ),
        problem(
            "L3ArpStormSegment",
            &[ScopeType::Session, ScopeType::Vlan],
            "l3_arp_storm_segment",
            None,
        ),
        problem(
            "L3NdpIpv6Visibility",
            &[ScopeType::Session],
            "l3_ndp_ipv6_visibility",
            None,
        ),
        problem(
            "L3DhcpDnsEdge",
            &[ScopeType::Session, ScopeType::Vlan],
            "l3_dhcp_dns_edge",
            None,
        ),
        problem(
            "L3DnsResolution",
            &[ScopeType::Session],
            "l3_dns_resolution",
            None,
        ),
        problem(
            "L3DnsTlsConsistency",
            &[ScopeType::Session],
            "l3_dns_tls_consistency",
            None,
        ),
        problem("L3TlsHsSlow", &[ScopeType::Session], "l3_tls_hs_slow", None),
        problem(
            "L3HttpRedirectChain",
            &[ScopeType::Session],
            "l3_http_redirect_chain",
            None,
        ),
        problem(
            "L3QuicCoexistPath",
            &[ScopeType::Session],
            "l3_quic_coexist_path",
            None,
        ),
        problem(
            "L3MulticastLan",
            &[ScopeType::Session, ScopeType::Vlan],
            "l3_multicast_lan",
            None,
        ),
        problem(
            "L3ZeroconfNoise",
            &[ScopeType::Session, ScopeType::Vlan],
            "l3_zeroconf_noise",
            None,
        ),
        problem(
            "L3VlanStackVisibility",
            &[ScopeType::Session, ScopeType::Vlan],
            "l3_vlan_stack_visibility",
            None,
        ),
        problem(
            "L3NtpChatter",
            &[ScopeType::Session],
            "l3_ntp_chatter",
            None,
        ),
        problem(
            "L3LldpContext",
            &[ScopeType::Session],
            "l3_lldp_context",
            None,
        ),
        // v1.2 (additive): Session-scoped variants for legacy L3 families whose
        // seed problems (SpanningTreeInstability, ClientOnboardingFailure) are
        // Vlan-scoped and cannot be emitted from Session decision rules.
        problem(
            "L3StpSpanningTree",
            &[ScopeType::Session],
            "l3_stp_spanning_tree",
            None,
        ),
        problem(
            "L3Dot1xWired",
            &[ScopeType::Session],
            "l3_dot1x_wired",
            None,
        ),
        // --- Protocol problems (legacy sarif_id families) ---
        problem(
            "RadiusHighReject",
            &[ScopeType::Global],
            "radius_high_reject",
            None,
        ),
        problem(
            "RadiusRetrans",
            &[ScopeType::Global],
            "radius_retrans",
            None,
        ),
        problem(
            "RadiusSlowAuth",
            &[ScopeType::Global],
            "radius_slow_auth",
            None,
        ),
        problem(
            "DiameterCerNoCea",
            &[ScopeType::Global],
            "diameter_cer_no_cea",
            None,
        ),
        problem(
            "DiameterWatchdogUnanswered",
            &[ScopeType::Global],
            "diameter_watchdog_unanswered",
            None,
        ),
        problem(
            "DiameterResultErrors",
            &[ScopeType::Global],
            "diameter_result_errors",
            None,
        ),
        problem(
            "DiameterMalformed",
            &[ScopeType::Global],
            "diameter_malformed",
            None,
        ),
        problem(
            "DiameterSessionTermImbalance",
            &[ScopeType::Global],
            "diameter_session_term_imbalance",
            None,
        ),
        problem(
            "GtpCreateSessionFailures",
            &[ScopeType::Global],
            "gtp_create_session_failures",
            None,
        ),
        problem(
            "GtpEchoUnanswered",
            &[ScopeType::Global],
            "gtp_echo_unanswered",
            None,
        ),
        problem(
            "GtpDeleteSessionImbalance",
            &[ScopeType::Global],
            "gtp_delete_session_imbalance",
            None,
        ),
        problem(
            "GtpModifySessionImbalance",
            &[ScopeType::Global],
            "gtp_modify_session_imbalance",
            None,
        ),
        problem("GtpUserOnly", &[ScopeType::Global], "gtp_user_only", None),
        problem("DhcpHighNak", &[ScopeType::Global], "dhcp_high_nak", None),
        problem(
            "DhcpMissingOffer",
            &[ScopeType::Global],
            "dhcp_missing_offer",
            None,
        ),
        problem(
            "DhcpSlowLease",
            &[ScopeType::Global],
            "dhcp_slow_lease",
            None,
        ),
    ]
    .into_iter()
    .chain(wifi::wifi_problems())
    .collect()
}
